// Code generated by command: go run asm-lzcnt64.go -out lzcnt64_amd64.s -stubs lzcnt64.go. DO NOT EDIT.

package lzcnt

// Using lzcnt to count Leading zeros of an uint64.
func lzcnt64(v uint64) int
