// Code generated by command: go run asm-lzcnt64.go -out lzcnt64_amd64.s -stubs lzcnt64.go. DO NOT EDIT.

#include "textflag.h"

// func lzcnt64(v uint64) int
// Requires: LZCNT
TEXT ·lzcnt64(SB), NOSPLIT, $0-16
	MOVQ   v+0(FP), AX
	LZCNTQ AX, AX
	MOVQ   AX, ret+8(FP)
	RET
